### ISSUE TITLE
Plugin added; "Run As" options not visible

### ISSUE THREAD

**Issue by pmbanka** [JetBrains/teamcity-runas-plugin#26]
I'm struggling to add this plugin to TeamCity 10.0.2 (build 42234). I built the plugin and then manually added `teamcity-plugin.xml` to generated zip package (without that, TC complains about it missing).

The plugin is unpacekd and visible in the plugin list:

![image](https://cloud.githubusercontent.com/assets/9840334/23988379/4f47e0a8-0a2e-11e7-8fba-01de51bb18d1.png)

yet there are no options related to it, neither in Build Step nor in Build Features.

Is there something I need to do in order to enable the plugin?

**Comment by meriturva** [comment]
The same here with teamcity 10.0.5 (TeamCity Enterprise license)

**Comment by NikolayPianikov** [comment]
To enable UI set the server [internal property](https://confluence.jetbrains.com/display/TCD10/Configuring+TeamCity+Server+Startup+Properties) "teamcity.runAs.ui.enabled" to "True"

**Comment by NikolayPianikov** [comment]
Now teamcity.runAs.ui.enabled is True by default

**Comment by dmitry-weirdo** [comment]
@NikolayPianikov 
Build fails immediately with "RunAs is not enabled".
I set it both in Build Configuration → Parameters (tried all 3 types) and also in Internal properties.
TeamCity version is 2017.1.5 (build 47175).

**Comment by NikolayPianikov** [comment]
@dmitry-weirdo you should configure your TeamCity agent's Windows account, see [this page](https://github.com/JetBrains/teamcity-runas-plugin/wiki/How-to-install) for details

**Comment by ndubbala** [comment]
i am facing in linux

**Comment by djkerya** [comment]
Installed plugin and don't see runas build feature. 2022.04.1 (build 108575) . Tried to add in  internal.properties with no luck
