### ISSUE TITLE
Can't install on TeamCity TeamCity Professional 2017.2.3 (build 51047)

### ISSUE THREAD

**Issue by bradmccormack** [JetBrains/teamcity-runas-plugin#31]
Zip runAs.zip contains invalid agent plugin xml

Possibly related to Plugins Packaging changes https://confluence.jetbrains.com/display/TCD10/Plugins+Packaging#PluginsPackaging-PluginDescriptor

**Comment by VladRassokhin** [comment]
@bradmccormack Please attach logs covering the issue

**Comment by bradmccormack** [comment]
@VladRassokhin it was a transient error.  I didn't capture the logs yesterday sorry. I restarted the TeamCity Server service and the problem was resolved.

Thanks.

**Comment by bradmccormack** [comment]
@VladRassokhin I was trying to install it via zip under the Tools section not plugins :-|

My fault.
