### ISSUE TITLE
RunAs not listed in build features

### ISSUE THREAD

**Issue by wardbox** [JetBrains/teamcity-runas-plugin#36]
**Plugin version**
![image](https://user-images.githubusercontent.com/31261302/78044046-013f4b00-7329-11ea-8ada-bd3134315bb4.png)

**Internal property**
![image](https://user-images.githubusercontent.com/31261302/78044114-174d0b80-7329-11ea-89d5-c44f0c047b79.png)

**TeamCity Server version**
![image](https://user-images.githubusercontent.com/31261302/78044134-1c11bf80-7329-11ea-9462-1d8c65240818.png)

**Missing build feature**
![image](https://user-images.githubusercontent.com/31261302/78044190-30ee5300-7329-11ea-8066-821c5fc69334.png)

I have installed the most recent version I could find. I can't see the RunAs option listed in the build feature dropdown.

**Comment by NikolayPianikov** [comment]
@wardbox Could you make a screenshot of your external plugin list (Administration->Plugins List)

**Comment by wardbox** [comment]
Feel free to close this, I no longer work at the company with the issue

**Comment by kyryloivanov** [comment]
I have the same issue
