### ISSUE TITLE
Support Unix OS

### ISSUE THREAD

**Issue by NikolayPianikov** [JetBrains/teamcity-runas-plugin#6]
runAs plugin should support unix OS

**Comment by nishaatr** [comment]
Please include testing on Redhat REL6 and 7, if possible,

**Comment by NikolayPianikov** [comment]
@nishaatr I've added the new issue for Radhat https://github.com/JetBrains/teamcity-runas-plugin/issues/10

**Comment by NikolayPianikov** [comment]
Tests for others Linux OS and for some specific build steps will be done in other tasks
