### ISSUE TITLE
Running individual build steps under the specified user's account

### ISSUE THREAD

**Issue by NikolayPianikov** [JetBrains/teamcity-runas-plugin#7]

**Comment by nishaatr** [comment]
1. The individual steps should be available for Windows and Linux. 
2. If possible, users should be able to execute steps like MSBuild, Maven, Commandline, PowerShell etc under given RunAs user.

**Comment by Kobaltauge** [comment]
Found this closed issue, but not an option to say which individual build step should use these option.
Please update the documentation.
