### ISSUE TITLE
Enhance RunAs GUI

### ISSUE THREAD

**Issue by nishaatr** [JetBrains/teamcity-runas-plugin#8]
1. Provide ability to change integrity level via drop down. 
2.  Provide ability to change log level via drop down. 
3. If possible provide drop down menu for other RunAs commandline options.

**Comment by NikolayPianikov** [comment]
@nishaatr What do you mean in this point? "If possible provide drop down menu for other RunAs commandline options." I've closed this issue. Feel free to add new for other requirements
